variables:
  BIRD2_VERSION: 2.0.10

build:
  image: registry.zotha.de/lukas/bird2-for-edgeos:stretch
  script:
    - wget -qO bird2.tar.gz http://deb.debian.org/debian/pool/main/b/bird2/bird2_${BIRD2_VERSION}.orig.tar.gz
    - tar -xzf bird2.tar.gz
    - cd bird-2*
    - CC=mips-linux-gnu-gcc-6 ./configure --host mips-linux --prefix /usr
    - CC=mips-linux-gnu-gcc-6 make -j 2
    - mv {bird,birdc,birdcl} ../bird2-for-edgeos/e100/usr/sbin
    - cd ../bird2-for-edgeos
    - tar --exclude='.[^/]*' --owner=0 --group=0 -cvzf bird2-e100.tar.gz -C e100 .
  artifacts:
    name: bird2-pkg
    paths:
      - bird2-e100.tar.gz
